### ISSUE TITLE
Filter clarification

### ISSUE THREAD

**Issue by MitsuhideA** [Kriegslustig/rss-o-bot#12]
Hello!
It seems that the filters work with a "AND" logic.
Is it intended? It would be much more convenient to use a "OR" logic. Maybe it should be an option to select when adding filters.

**Comment by Kriegslustig** [comment]
Yeah, you're probably right. Currently testing the new version. I'll publish it once I'm done.

**Comment by halbgut** [comment]
New version published. Closing this issue.

**Comment by ZakYahi** [comment]
Thank you!
