### ISSUE TITLE
more logs please

### ISSUE THREAD

**Issue by sebs** [Kriegslustig/rss-o-bot#8]
when debugging 

* how many are found 
* when updatedAt is written, please log in debug
* log received parameters in debug (convenience) 

Ah .. thanks for the tool btw ;)

**Comment by Kriegslustig** [comment]
Thanks for your suggestions. :)

I've implemented you're last two suggestions and released RC 13 version.

> how many are found

It should log `New URL: [...]` for every new URL. Do you mean the total count of new links?

**Comment by sebs** [comment]
<3

**Comment by sebs** [comment]
<3
